name: Unit Tests

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.md"
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  run_tests:
    name: Run tests
    runs-on: macos-13
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
      - name: Run tests
        run: |
          swift test
